### ISSUE TITLE
Error in fresh installation 

### ISSUE THREAD

**Issue by m-gamal** [alariva/timegrid#52]
When I install this app , suddenly I saw this error "Fatal error: Uncaught exception 'ReflectionException' with message 'Class log does not exist'" . I don't have any idea about this error in this fresh installation . How to fix it ?

**Comment by alariva** [comment]
At this point I have very little information about the problem you are facing.
Are you installing the latest stable commit?

**Comment by alariva** [comment]
[Discussion here](https://gitter.im/alariva/timegridDevelopment?at=56ab4e838fbaf4220afa0f9a)

Try running `composer install --dev` instead of `composer install`

Installing instructions were updated and [troubleshooting](https://github.com/alariva/timegrid/blob/master/TROUBLESHOOTING.md) section added.
